version: '3.1'

volumes:
    prometheus_data:
    grafana_data:

networks:
  cc-exporter-stack:

services:

  prometheus:
    image: prom/prometheus:v2.22.0
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./prometheus/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 127.0.0.1:9090:9090
    networks:
      - cc-exporter-stack

  cc-exporter:
    image: cc-exporter:latest
    build: ./
    environment:
      - COINCAPURL=https://api.coincap.io/v2/assets
      - INTERVAL=50
      - CRYPTOS=ethereum,bitcoin,xrp,binance-coin,stellar,tether
      - APP_PORT=5000
    ports:
        - 127.0.0.1:5000:5000
    networks:
        - cc-exporter-stack


  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/grafana_data/:/var/lib/grafana
    environment: 
      - GF_PATHS_CONFIG=/etc/grafana/provisioning/grafana.ini
    networks:
      - cc-exporter-stack
