{
 "title": "CC-Exporter",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "COIN", "label": "coin", "query": "label_values(name)" }
  ]
 },
 "panels": [
  {
   "title": "Rank",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cc_exporter_rank{name=~\"$COIN\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Price USD",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cc_exporter_priceUsd{name=~\"$COIN\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "24h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cc_exporter_changePercent24Hr{name=~\"$COIN\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "24h",
   "type": "graph",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cc_exporter_changePercent24Hr{name=~\"$COIN\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Market Cap",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cc_exporter_marketCapUsd{name=~\"$COIN\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Volume 24h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cc_exporter_volumeUsd24Hr{name=~\"$COIN\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Supply",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cc_exporter_supply{name=~\"$COIN\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$COIN Chart",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "cc_exporter_priceUsd{name=~\"$COIN\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Market Cap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "cc_exporter_marketCapUsd{name=~\"$COIN\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Volume 24h",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "cc_exporter_volumeUsd24Hr{name=~\"$COIN\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Supply - Max Supply",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "cc_exporter_supply{name=~\"$COIN\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "cc_exporter_maxSupply{name=~\"$COIN\"}",
     "legendFormat": "MS {{name}}"
    }
   ]
  }
 ]
}